/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalbd;

/**
 *
 * @author LuFitz
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reportesP = new javax.swing.JPanel();
        reportesB = new javax.swing.JLabel();
        productosP = new javax.swing.JPanel();
        productosB = new javax.swing.JLabel();
        ventasP = new javax.swing.JPanel();
        ventasB = new javax.swing.JLabel();
        sucursalesP = new javax.swing.JPanel();
        sucursalesB = new javax.swing.JLabel();
        salirP = new javax.swing.JPanel();
        DetalleVentas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setName("backgroud"); // NOI18N
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pixlr-bg-result (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 390, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu1.png"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 290, 590));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/punto-de-venta.png"))); // NOI18N
        jLabel3.setText("Punto de venta");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Seleccione la opcion que necesite");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 410, -1));

        reportesP.setBackground(new java.awt.Color(12, 78, 140));

        reportesB.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        reportesB.setForeground(new java.awt.Color(255, 255, 255));
        reportesB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportesB.setText("Reportes");
        reportesB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportesB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportesB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportesBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reportesPLayout = new javax.swing.GroupLayout(reportesP);
        reportesP.setLayout(reportesPLayout);
        reportesPLayout.setHorizontalGroup(
            reportesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportesB, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        reportesPLayout.setVerticalGroup(
            reportesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportesB, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        background.add(reportesP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 150, 70));

        productosP.setBackground(new java.awt.Color(79, 231, 175));

        productosB.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        productosB.setForeground(new java.awt.Color(255, 255, 255));
        productosB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productosB.setText("Productos");
        productosB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productosB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        productosB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout productosPLayout = new javax.swing.GroupLayout(productosP);
        productosP.setLayout(productosPLayout);
        productosPLayout.setHorizontalGroup(
            productosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productosB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        productosPLayout.setVerticalGroup(
            productosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productosB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        background.add(productosP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 70));

        ventasP.setBackground(new java.awt.Color(17, 196, 212));

        ventasB.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ventasB.setForeground(new java.awt.Color(255, 255, 255));
        ventasB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventasB.setText("Ventas");
        ventasB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ventasB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ventasB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventasBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ventasPLayout = new javax.swing.GroupLayout(ventasP);
        ventasP.setLayout(ventasPLayout);
        ventasPLayout.setHorizontalGroup(
            ventasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventasB, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        ventasPLayout.setVerticalGroup(
            ventasPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventasB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        background.add(ventasP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 150, 70));

        sucursalesP.setBackground(new java.awt.Color(12, 129, 228));

        sucursalesB.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        sucursalesB.setForeground(new java.awt.Color(255, 255, 255));
        sucursalesB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sucursalesB.setText("Sucursales");
        sucursalesB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sucursalesB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sucursalesB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sucursalesBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sucursalesPLayout = new javax.swing.GroupLayout(sucursalesP);
        sucursalesP.setLayout(sucursalesPLayout);
        sucursalesPLayout.setHorizontalGroup(
            sucursalesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sucursalesB, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        sucursalesPLayout.setVerticalGroup(
            sucursalesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sucursalesB, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        background.add(sucursalesP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 150, 70));

        salirP.setBackground(new java.awt.Color(239, 216, 203));

        DetalleVentas.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        DetalleVentas.setForeground(new java.awt.Color(255, 255, 255));
        DetalleVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DetalleVentas.setText("Detalle Ventas");
        DetalleVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DetalleVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DetalleVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetalleVentasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salirPLayout = new javax.swing.GroupLayout(salirP);
        salirP.setLayout(salirPLayout);
        salirPLayout.setHorizontalGroup(
            salirPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DetalleVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        salirPLayout.setVerticalGroup(
            salirPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DetalleVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        background.add(salirP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 180, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DetalleVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetalleVentasMouseClicked
       DetalleVentas ventana = new DetalleVentas();
       ventana.setVisible(true);
    }//GEN-LAST:event_DetalleVentasMouseClicked

    private void productosBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosBMouseClicked
        MenuProductos ventana = new MenuProductos();
        ventana.setVisible(true);
    }//GEN-LAST:event_productosBMouseClicked

    private void ventasBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasBMouseClicked
        Ventas ventana = new Ventas();
        ventana.setVisible(true);
    }//GEN-LAST:event_ventasBMouseClicked

    private void sucursalesBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sucursalesBMouseClicked
        Sucursales ventana = new Sucursales();
        ventana.setVisible(true);
    }//GEN-LAST:event_sucursalesBMouseClicked

    private void reportesBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesBMouseClicked
        Reportes ventana = new Reportes();
        ventana.setVisible(true);
    }//GEN-LAST:event_reportesBMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetalleVentas;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel productosB;
    private javax.swing.JPanel productosP;
    private javax.swing.JLabel reportesB;
    private javax.swing.JPanel reportesP;
    private javax.swing.JPanel salirP;
    private javax.swing.JLabel sucursalesB;
    private javax.swing.JPanel sucursalesP;
    private javax.swing.JLabel ventasB;
    private javax.swing.JPanel ventasP;
    // End of variables declaration//GEN-END:variables
}
